site_name: CHrisGray
site_description: 'Chris Gray'

# Info : https://squidfunk.github.io/mkdocs-material/

theme:
    name: material
    features:
        - navigation.top
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        # - content.code.select
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.footer
        - navigation.indexes
        # - navigation.instant
        # - navigation.instant.prefetch
        # - navigation.instant.progress
        # - navigation.prune
        # - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        # - toc.integrate
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/link
            name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/toggle-switch
            name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: indigo
          toggle:
              icon: material/toggle-switch-off
              name: Switch to system preference
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/favicon.png
    icon:
        logo: logo

nav:
    - Introduction: index.md
    - Posts:
      - AI Document Editor: Blog.AI.DocumentEditor.md

plugins:
    - search
    - mermaid2
    - include-markdown:
        encoding: ascii
        preserve_includer_indent: false
        dedent: false
        trailing_newlines: true
        comments: true
        rewrite_relative_urls: true
        heading_offset: 0
        start: //<!--start-->
        end: //<!--end-->
        recursive: true


markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.details:
      types:
      - name: details-new
        class: new
      - name: details-settings
        class: settings
      - name: details-note
        class: note
      - name: details-abstract
        class: abstract
      - name: details-info
        class: info
      - name: details-tip
        class: tip
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote

extra_css:
    - extra.css

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js